title: Steven Akoko
email: akokosteven19@gmail.com
description: >- 
  IT and Cybersecurity Professional Portfolio | Cloud Security | IT Support | DevSecOps Enthusiast
minimal_mistakes_skin: mint
search: true

remote_theme: mmistakes/minimal-mistakes

markdown: kramdown
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Africa/Nairobi

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Steven Akoko"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "IT & Cybersecurity Specialist | Cloud Security | Support Engineer"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/steven-akoko"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://shorturl.at/FE4Ly"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:akokosteven19@gmail.com"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/steven-akoko"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://shorturl.at/FE4Ly"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:akokosteven19@gmail.com"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
